import type { Gotcha } from '../components/GotchaWall';

const issue = (n: number) => ({ href: `https://github.com/huggingface/lerobot/issues/${n}`, label: `#${n}` });
const pr = (n: number) => ({ href: `https://github.com/huggingface/lerobot/pull/${n}`, label: `PR #${n}` });

// From the community research of 2026-10-06 (issues, PRs, HF forum). Counts as read that day.
export const LEROBOT_GOTCHAS: Gotcha[] = [
  {
    status: 'open',
    area: 'training speed',
    title: 'Training is bound by video decode',
    body: 'GPUs sit idle while dataloader workers decode MP4. One profile in the thread puts decode at 92% of per-sample time. The most-discussed open issue on the data side (25 comments).',
    fix: 'Raise `num_workers`, keep data local, and watch the batched-reader work (PR #4549) and the roadmap items for batched and GPU decode.',
    links: [issue(1488), pr(4549), issue(3832)],
  },
  {
    status: 'open',
    area: 'streaming',
    title: 'Streaming can read the wrong frames on multi-file datasets',
    body: '`StreamingLeRobotDataset` computes the video timestamp from the dataset-wide frame index (`index / fps`), not the position inside the episode\'s file. Large datasets crash with "Invalid frame index"; others may return wrong frames silently.',
    fix: 'Use the map-style `LeRobotDataset` for multi-file datasets until a fix lands (PRs #4702, #4528), and spot-check decoded frames.',
    links: [issue(4524), issue(3080), issue(2649), pr(4702)],
  },
  {
    status: 'open',
    area: 'format design',
    title: 'One fps per dataset, by design',
    body: 'Mixed rates and real hardware timestamps are not supported. A maintainer: training VLAs "require synchronous \'snapshots\' of the robotic system at each 1/fps". Datasets with hardware timestamps crash in decode.',
    fix: 'Resample every stream onto one grid before writing. That is the time-sync step on this page.',
    links: [issue(3513), issue(4368)],
  },
  {
    status: 'open',
    area: 'recording',
    title: 'Recording can drop frames without telling you',
    body: 'Under load the async image writer could drop frames silently, leaving cameras misaligned after encoding. Streaming encoding drops frames by design when its queue is full.',
    fix: 'Compare frame counts per camera after each episode. Raise `encoder_threads` or `encoder_queue_maxsize`, or use a hardware encoder.',
    links: [pr(4533), { href: 'https://github.com/huggingface/lerobot/blob/main/docs/source/streaming_video_encoding.mdx', label: 'streaming encoding docs' }],
  },
  {
    status: 'open',
    area: 'rosbag / MCAP',
    title: 'No official path from ROS bags or MCAP',
    body: 'An open RFC surveys ROS 2 integration and lists third-party converters whose v3 output is unaudited. The roadmap marks MCAP as "TBD".',
    fix: 'Treat converters as a starting point: check fps, frame counts, names and stats on the output before training.',
    links: [issue(4368), issue(3832)],
  },
  {
    status: 'open',
    area: 'versions',
    title: 'v2.0, v2.1 and v3.0 datasets coexist on the Hub',
    body: 'Hundreds of LIBERO variants alone, some still v2.0, and no v2.0 to v3.0 script. The v2.1 to v3.0 converter runs sequentially; a parallel version has been open since 2025.',
    fix: 'Check `codebase_version` in `meta/info.json` before you build on a dataset. Streaming only accepts v3.0.',
    links: [issue(2446), issue(1998)],
  },
  {
    status: 'open',
    area: 'editing',
    title: 'Merging needs identical features, and reindexing is slow',
    body: '`merge_datasets` requires the same feature keys and shapes. One user reports about 8 hours to reindex metadata for ~10k episodes. Nested array columns break merge and split.',
    fix: 'Normalize feature names and shapes before merging; merge in batches.',
    links: [issue(3596), issue(2445), issue(2326)],
  },
  {
    status: 'open',
    area: 'stats',
    title: 'Merged quantile stats are approximate',
    body: 'Merging averages per-source q01/q99 weighted by frame count, which is not the quantile of the merged data. Some merged stats (task_index) go stale.',
    fix: 'Recompute stats on the merged dataset (`recompute_stats` in `dataset_tools`) before training with quantile normalization.',
    links: [issue(4156), issue(3788)],
  },
  {
    status: 'open',
    area: 'multi-dataset',
    title: 'Training on several datasets means merging first',
    body: '`MultiLeRobotDataset` exists, but the training config takes a single `repo_id`. Weighted sampling, key mapping and per-robot stats are roadmap items.',
    fix: 'Merge into one dataset with shared feature keys, or write your own sampler.',
    links: [issue(1576), issue(2259)],
  },
  {
    status: 'workaround',
    area: 'timestamps',
    title: 'FrameTimestampError: "violate the tolerance"',
    body: 'Most often a stale or corrupt local copy of a Hub dataset; also timestamps off the 1/fps grid or drift in concatenated videos.',
    fix: 'Delete `~/.cache/huggingface/lerobot` and re-download. If it persists, check that timestamps are `frame_index / fps`.',
    links: [issue(1875), issue(3177)],
  },
  {
    status: 'workaround',
    area: 'Hub',
    title: 'The default revision can lag the Hub',
    body: '`LeRobotDataset` loads the v3.0 tag by default. On some datasets the tag is behind main (one example: 1 task on the tag, 4,219 on main).',
    fix: 'Pass `revision=` explicitly and record it with your training run.',
    links: [issue(4017)],
  },
  {
    status: 'workaround',
    area: 'install',
    title: 'ffmpeg and torchcodec have to match',
    body: 'If `libsvtav1` is missing or torchcodec fails to load, decoding breaks or falls back to slower pyav. torchcodec is unavailable on some platforms, including Jetson builds.',
    fix: 'Install ffmpeg 7.1.1 when the default build lacks `libsvtav1`, or set `video_backend="pyav"`.',
    links: [{ href: 'https://github.com/huggingface/lerobot/blob/main/docs/source/installation.mdx', label: 'install docs' }, issue(2363)],
  },
  {
    status: 'fixed',
    area: 'training speed',
    title: 'delta_timestamps was up to 40x slower',
    body: 'Fixed on main on Sep 1, 2026. The latest PyPI release (0.6.1, Aug 3) does not have it.',
    fix: 'Install from main if you train with action chunks and see slow loading.',
    links: [issue(2895), pr(4314)],
  },
  {
    status: 'fixed',
    area: 'conversion',
    title: 'Early v3.0 conversions can carry wrong file indices',
    body: 'The v2.1 to v3.0 converter wrote stale file indices for the episode that rolls over into a new file. The script is fixed; datasets already converted and uploaded stay wrong.',
    fix: 'Re-convert from the v2.1 source, or validate episode boundaries before training.',
    links: [issue(2401), pr(2941)],
  },
  {
    status: 'fixed',
    area: 'depth',
    title: 'Depth arrived in v0.6.0, as 12-bit video',
    body: 'Depth images were the most requested feature (31 comments, 21 reactions). Support landed in v0.6.0, quantized to 12 bits in video.',
    fix: 'Set `depth_min` and `depth_max` to the sensor\'s real range; values outside saturate.',
    links: [issue(1144), pr(3644)],
  },
];
